### ISSUE TITLE
Create form components

### ISSUE THREAD

**Issue by belgamo** [Codeminer42/punch_clock_mobile#18]
We need to create generic components for our app forms such as buttons, text inputs, and selects. Consider taking a look at the Figma file and try to match the design as close as possible.

https://www.figma.com/file/qQvHEsZ7td7f9UHYHlkLxB/PunchClock-Mobile-App

Also, would be great to have a [wrapper](https://react-hook-form.com/get-started#ReactNative) for `react-hook-form` so we can easily consume that over the app.

**Comment by JRRGomes** [comment]
I'd like to do this during the refactoring of this PR: https://github.com/Codeminer42/punch_clock_mobile/pull/12
Is that a good option?

**Comment by joaoGabriel55** [comment]
I'm creating a page with only base components on Figma @JRRGomes, you can take a look.

https://www.figma.com/file/qQvHEsZ7td7f9UHYHlkLxB/PunchClock-Mobile-App?node-id=522%3A2
