### ISSUE TITLE
Finish login screen

### ISSUE THREAD

**Issue by belgamo** [Codeminer42/punch_clock_mobile#30]
We have the wrapper for this screen already. We just to add the e-mail and password fields that are controlled by react-hook-form.

Please, whoever take this task, rename the following components:
- `input-form` to `rhf-input`
- `selected-form` to `rhf-select`

**Comment by aq-simei** [comment]
I would like to try solving this issue.

**Comment by belgamo** [comment]
> I would like to try solving this issue.

Hey, this is done. I'll close the issue.
